# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: releases.proto

require 'google/protobuf'

require 'google/api/annotations'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "releaser.ChannelReleases" do
    optional :Channel, :message, 1, "releaser.Channel"
    repeated :Releases, :message, 2, "releaser.Release"
  end
  add_message "releaser.Release" do
    optional :ID, :string, 1
    optional :SHA, :string, 2
  end
  add_message "releaser.Channel" do
    optional :ID, :string, 1
    optional :Name, :string, 2
  end
  add_message "releaser.ChannelReleaseRequest" do
    optional :ChannelID, :string, 1
  end
  add_message "releaser.ReleaseRequest" do
    optional :ReleaseID, :string, 1
  end
  add_message "releaser.AddReleaseResponse" do
    optional :ReleaseID, :string, 1
  end
end

module Releaser
  ChannelReleases = Google::Protobuf::DescriptorPool.generated_pool.lookup("releaser.ChannelReleases").msgclass
  Release = Google::Protobuf::DescriptorPool.generated_pool.lookup("releaser.Release").msgclass
  Channel = Google::Protobuf::DescriptorPool.generated_pool.lookup("releaser.Channel").msgclass
  ChannelReleaseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("releaser.ChannelReleaseRequest").msgclass
  ReleaseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("releaser.ReleaseRequest").msgclass
  AddReleaseResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("releaser.AddReleaseResponse").msgclass
end
