# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service.proto for package 'releaser'

require 'grpc'
require 'service'

module Releaser
  module Releases
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'releaser.Releases'

      rpc :GetChannelReleases, ChannelReleaseRequest, ChannelReleases
      rpc :GetRelease, ReleaseRequest, Release
    end

    Stub = Service.rpc_stub_class
  end
end
